# Generated by Django 2.1.2 on 2019-01-29 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='active_key',
            field=models.CharField(blank=True, max_length=120, verbose_name='код подтверждения'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 22, 22, 56, 913242, tzinfo=utc)),
        ),
    ]
