# Generated by Django 2.1.5 on 2019-02-02 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190129_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 18, 30, 43, 703936, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
